// <auto-generated />
using System;
using DotNetStarter.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetStarter.Migrations
{
    [DbContext(typeof(DotNetStarterDbContext))]
    [Migration("20230924142840_Adjust UserModel")]
    partial class AdjustUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetStarter.Entities.Otp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("DotNetStarter.Entities.Privilege", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9192d5a9-4c14-4476-bed7-4adfaf3143a1"),
                            Name = "MANAGE_USERS"
                        },
                        new
                        {
                            Id = new Guid("9e78bf4f-5755-4de6-a9f1-eb55e128fce3"),
                            Name = "MANAGE_PAID_LINGUISTIC_ASSETS"
                        },
                        new
                        {
                            Id = new Guid("28f71db9-0a42-4d46-9598-8ae23757d93c"),
                            Name = "MANAGE_VENDORS"
                        },
                        new
                        {
                            Id = new Guid("0b86be03-3108-45b2-9395-9fff73196dc7"),
                            Name = "MANAGE_CLIENTS_AND_PROJECT_TAGS"
                        },
                        new
                        {
                            Id = new Guid("3dd1ace0-2705-4506-9e5c-af0fca494249"),
                            Name = "CREATE_ANY_PROJECTS"
                        },
                        new
                        {
                            Id = new Guid("bb69557d-f2e0-494a-8d22-c22804365f28"),
                            Name = "VIEW_ALL_PROJECTS"
                        },
                        new
                        {
                            Id = new Guid("b52c6097-8351-40a9-a292-d63a38fd33de"),
                            Name = "MANAGE_LINGUISTIC_ASSETS_IN_ALL_PROJECTS"
                        },
                        new
                        {
                            Id = new Guid("d1c79973-6bc7-412f-a36a-322896caca37"),
                            Name = "MANAGE_ALL_GLOSSARIES"
                        },
                        new
                        {
                            Id = new Guid("ec6da46f-856f-4ba6-bcfa-f83b7b76d0dc"),
                            Name = "MANAGE_ALL_TMS"
                        },
                        new
                        {
                            Id = new Guid("6f486878-dc77-45d3-9c4e-da2754084e2d"),
                            Name = "SUGGEST_TERMS_WITHOUT_SPECIFYING_A_GLOSSARY"
                        },
                        new
                        {
                            Id = new Guid("8bef0e9b-3ef5-48fd-8dcf-c1314474f94f"),
                            Name = "MANAGE_PROJECT_TEMPLATES"
                        },
                        new
                        {
                            Id = new Guid("f7f1930a-e9f0-4e86-aefb-80a53bac54f3"),
                            Name = "MANAGE_ORDERS"
                        },
                        new
                        {
                            Id = new Guid("7ec9f54f-785b-4044-a760-a74468e81a7e"),
                            Name = "MANAGE_SERVICE_TEMPLATES"
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            Name = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            Name = "PROJECT_MANAGER"
                        },
                        new
                        {
                            Id = new Guid("86a71f44-f797-41d7-ab6e-a19cb24c6c77"),
                            Name = "RESOURCE_MANAGER"
                        },
                        new
                        {
                            Id = new Guid("20605041-b02f-487d-9346-0d7ca10e44d9"),
                            Name = "LOCALIZATION_TEAM"
                        },
                        new
                        {
                            Id = new Guid("6faf71df-2619-4373-9835-82821b31bc25"),
                            Name = "TALENT"
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.RolePrivilege", b =>
                {
                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrivilegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("RolePrivileges");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("9192d5a9-4c14-4476-bed7-4adfaf3143a1"),
                            Id = new Guid("642c08ef-e58e-44db-977a-4fccd251d4ef")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("9e78bf4f-5755-4de6-a9f1-eb55e128fce3"),
                            Id = new Guid("7d7e91d6-bbb1-4bbd-a659-bf03a34b717b")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("28f71db9-0a42-4d46-9598-8ae23757d93c"),
                            Id = new Guid("b3782702-74ab-43c8-86c2-b2bd1c2d91aa")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("0b86be03-3108-45b2-9395-9fff73196dc7"),
                            Id = new Guid("4698beea-891b-413c-94d2-63d14b680fd5")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("3dd1ace0-2705-4506-9e5c-af0fca494249"),
                            Id = new Guid("6433e0e5-840d-4a5b-b65d-f098f0d7ea62")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("bb69557d-f2e0-494a-8d22-c22804365f28"),
                            Id = new Guid("9e4366a2-0463-479d-929b-fe516394e1f9")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("b52c6097-8351-40a9-a292-d63a38fd33de"),
                            Id = new Guid("0d003362-5d3e-4010-af7e-0a3d17a45532")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("d1c79973-6bc7-412f-a36a-322896caca37"),
                            Id = new Guid("1763564d-4e78-4915-b128-4e592c2cef85")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("ec6da46f-856f-4ba6-bcfa-f83b7b76d0dc"),
                            Id = new Guid("bb8ddaf0-2073-4657-8f5f-10708bc56d5d")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("6f486878-dc77-45d3-9c4e-da2754084e2d"),
                            Id = new Guid("4ec6db11-f38b-4c8d-b46c-87d705413a3f")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("8bef0e9b-3ef5-48fd-8dcf-c1314474f94f"),
                            Id = new Guid("b75e4e4c-8510-46ec-b95b-19432ba02b2c")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("f7f1930a-e9f0-4e86-aefb-80a53bac54f3"),
                            Id = new Guid("71111bfb-8912-482e-abfc-01650ffd29b8")
                        },
                        new
                        {
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            PrivilegeId = new Guid("7ec9f54f-785b-4044-a760-a74468e81a7e"),
                            Id = new Guid("0d706aa0-aeff-4be5-aabd-17fb0e2402e5")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("0b86be03-3108-45b2-9395-9fff73196dc7"),
                            Id = new Guid("fdbe9202-70b0-4ed2-b3b8-944df2996e20")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("3dd1ace0-2705-4506-9e5c-af0fca494249"),
                            Id = new Guid("20e78899-c286-4f3f-a410-146e2a75d1fa")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("bb69557d-f2e0-494a-8d22-c22804365f28"),
                            Id = new Guid("f04077ca-9133-42c6-9b58-abd9ccfe4dc2")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("b52c6097-8351-40a9-a292-d63a38fd33de"),
                            Id = new Guid("e40f84b0-f960-4e6a-a4be-b12f5d90d3a8")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("d1c79973-6bc7-412f-a36a-322896caca37"),
                            Id = new Guid("4374d1f9-96bf-42e7-a3c3-2a48ba58733c")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("ec6da46f-856f-4ba6-bcfa-f83b7b76d0dc"),
                            Id = new Guid("02f6fbc2-69ef-4d6d-99da-c0b4d1482a38")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("6f486878-dc77-45d3-9c4e-da2754084e2d"),
                            Id = new Guid("218204b1-77f6-409d-8f0b-8e9791759fbb")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("8bef0e9b-3ef5-48fd-8dcf-c1314474f94f"),
                            Id = new Guid("def7dc94-6d2d-4f4c-85ec-2917edcc7c87")
                        },
                        new
                        {
                            RoleId = new Guid("8bad9fd7-2154-4472-b251-f3fe125bb355"),
                            PrivilegeId = new Guid("f7f1930a-e9f0-4e86-aefb-80a53bac54f3"),
                            Id = new Guid("6a452c8e-4c2e-4354-88c4-d5ded4c50783")
                        },
                        new
                        {
                            RoleId = new Guid("86a71f44-f797-41d7-ab6e-a19cb24c6c77"),
                            PrivilegeId = new Guid("d1c79973-6bc7-412f-a36a-322896caca37"),
                            Id = new Guid("b271f340-ae1d-421a-ac61-a4d0200e3d94")
                        },
                        new
                        {
                            RoleId = new Guid("86a71f44-f797-41d7-ab6e-a19cb24c6c77"),
                            PrivilegeId = new Guid("ec6da46f-856f-4ba6-bcfa-f83b7b76d0dc"),
                            Id = new Guid("12422b9b-9d92-4481-be66-b922ec2f24d3")
                        },
                        new
                        {
                            RoleId = new Guid("86a71f44-f797-41d7-ab6e-a19cb24c6c77"),
                            PrivilegeId = new Guid("6f486878-dc77-45d3-9c4e-da2754084e2d"),
                            Id = new Guid("d38aa996-1f12-4147-a797-a727cce31f6d")
                        },
                        new
                        {
                            RoleId = new Guid("20605041-b02f-487d-9346-0d7ca10e44d9"),
                            PrivilegeId = new Guid("d1c79973-6bc7-412f-a36a-322896caca37"),
                            Id = new Guid("4cf470b2-c6a2-47c5-9e50-59f4358524fe")
                        },
                        new
                        {
                            RoleId = new Guid("20605041-b02f-487d-9346-0d7ca10e44d9"),
                            PrivilegeId = new Guid("3dd1ace0-2705-4506-9e5c-af0fca494249"),
                            Id = new Guid("98226852-ee9d-4745-8a6d-0b66c7555faa")
                        },
                        new
                        {
                            RoleId = new Guid("20605041-b02f-487d-9346-0d7ca10e44d9"),
                            PrivilegeId = new Guid("bb69557d-f2e0-494a-8d22-c22804365f28"),
                            Id = new Guid("45eab76b-e7ed-4ba7-8bf6-ad157783561a")
                        },
                        new
                        {
                            RoleId = new Guid("20605041-b02f-487d-9346-0d7ca10e44d9"),
                            PrivilegeId = new Guid("ec6da46f-856f-4ba6-bcfa-f83b7b76d0dc"),
                            Id = new Guid("5e98fb19-750b-49df-9310-8100d3aa0604")
                        },
                        new
                        {
                            RoleId = new Guid("20605041-b02f-487d-9346-0d7ca10e44d9"),
                            PrivilegeId = new Guid("b52c6097-8351-40a9-a292-d63a38fd33de"),
                            Id = new Guid("a1d01b80-54ac-49e9-b801-a456a1a98ce0")
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("RoleId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2023, 9, 24, 21, 28, 39, 914, DateTimeKind.Local).AddTicks(4614),
                            Firstname = "Admin",
                            Gender = 1,
                            Lastname = "Yopmail",
                            Password = "$2a$11$/Ccuv/Dz0fks2yfQ/lsLU.P7xTtzPi9yl2v/rdUwiKmSNVzQYQWGy",
                            PhoneNumber = "0333333333",
                            RoleId = new Guid("2756e33b-7f24-452e-85fe-5a8bc3244f5e"),
                            Status = 1,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2023, 9, 24, 21, 28, 39, 914, DateTimeKind.Local).AddTicks(4614),
                            Username = "admin.dotnetstarter@yopmail.com"
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.UserPrivilege", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrivilegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("UserPrivileges");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("9192d5a9-4c14-4476-bed7-4adfaf3143a1"),
                            Id = new Guid("2799ddd5-4590-4855-b1c9-b732151db597")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("9e78bf4f-5755-4de6-a9f1-eb55e128fce3"),
                            Id = new Guid("fea9b621-65b2-4743-8bb6-d8a5440c9715")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("28f71db9-0a42-4d46-9598-8ae23757d93c"),
                            Id = new Guid("b8bd577e-dc4d-4834-91ca-925693183426")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("0b86be03-3108-45b2-9395-9fff73196dc7"),
                            Id = new Guid("9c453f74-5ad3-4e4b-8af6-3b49afd3af55")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("3dd1ace0-2705-4506-9e5c-af0fca494249"),
                            Id = new Guid("2a3f6622-5bfd-49e9-b89a-c36a4848516a")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("bb69557d-f2e0-494a-8d22-c22804365f28"),
                            Id = new Guid("33a9bda8-700b-4599-a9af-ad8d467e94e2")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("b52c6097-8351-40a9-a292-d63a38fd33de"),
                            Id = new Guid("25818f9a-05e3-48e6-9f0b-c0e0f42267ef")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("d1c79973-6bc7-412f-a36a-322896caca37"),
                            Id = new Guid("db091d7f-b019-40e8-bc2d-cbd96a1d9fd6")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("ec6da46f-856f-4ba6-bcfa-f83b7b76d0dc"),
                            Id = new Guid("37a44316-b776-49d8-98c8-b9d432dc3dfe")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("6f486878-dc77-45d3-9c4e-da2754084e2d"),
                            Id = new Guid("5c691944-52a9-416c-bd6b-cb9edb0472b2")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("8bef0e9b-3ef5-48fd-8dcf-c1314474f94f"),
                            Id = new Guid("124b789f-f51a-4431-afcc-8ac5acf3c405")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("f7f1930a-e9f0-4e86-aefb-80a53bac54f3"),
                            Id = new Guid("b45e1f57-31e1-4644-afe8-bb5045f3bed0")
                        },
                        new
                        {
                            UserId = new Guid("ed6a5f95-cdb8-471d-9018-92be865e3052"),
                            PrivilegeId = new Guid("7ec9f54f-785b-4044-a760-a74468e81a7e"),
                            Id = new Guid("cf9d870e-1b77-44bc-a626-aef69c4fcc31")
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.Otp", b =>
                {
                    b.HasOne("DotNetStarter.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetStarter.Entities.RolePrivilege", b =>
                {
                    b.HasOne("DotNetStarter.Entities.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetStarter.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotNetStarter.Entities.User", b =>
                {
                    b.HasOne("DotNetStarter.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotNetStarter.Entities.UserPrivilege", b =>
                {
                    b.HasOne("DotNetStarter.Entities.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetStarter.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
