// <auto-generated />
using System;
using DotNetStarter.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetStarter.Migrations
{
    [DbContext(typeof(DotNetStarterDbContext))]
    partial class DotNetStarterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetStarter.Entities.Otp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("DotNetStarter.Entities.Privilege", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76202262-ad72-41b1-9184-6c1934e0d85a"),
                            Name = "MANAGE_USERS"
                        },
                        new
                        {
                            Id = new Guid("51d3cc91-396d-4c1b-a400-3484dedaa21a"),
                            Name = "MANAGE_PAID_LINGUISTIC_ASSETS"
                        },
                        new
                        {
                            Id = new Guid("d50920b7-db8c-4300-9b10-c7f35febb5c7"),
                            Name = "MANAGE_VENDORS"
                        },
                        new
                        {
                            Id = new Guid("301940eb-2f5c-4d01-aa1a-01694da06a7c"),
                            Name = "MANAGE_CLIENTS_AND_PROJECT_TAGS"
                        },
                        new
                        {
                            Id = new Guid("f90b00af-b217-4714-b638-adcb9248e885"),
                            Name = "CREATE_ANY_PROJECTS"
                        },
                        new
                        {
                            Id = new Guid("63b82dde-6c06-4b2d-aeeb-32f4fb93b7ff"),
                            Name = "VIEW_ALL_PROJECTS"
                        },
                        new
                        {
                            Id = new Guid("489bbacf-f6ac-4a80-bf33-a89473839c5d"),
                            Name = "MANAGE_LINGUISTIC_ASSETS_IN_ALL_PROJECTS"
                        },
                        new
                        {
                            Id = new Guid("8e83760d-1a14-4d55-9fab-bd4ddc082894"),
                            Name = "MANAGE_ALL_GLOSSARIES"
                        },
                        new
                        {
                            Id = new Guid("5917352e-896c-4b77-a074-cabb3d6cae1b"),
                            Name = "MANAGE_ALL_TMS"
                        },
                        new
                        {
                            Id = new Guid("a8dcdd64-261a-4408-ad1c-905d580ebb82"),
                            Name = "SUGGEST_TERMS_WITHOUT_SPECIFYING_A_GLOSSARY"
                        },
                        new
                        {
                            Id = new Guid("9c8533af-3487-4fad-9667-2d93f5cc9fda"),
                            Name = "MANAGE_PROJECT_TEMPLATES"
                        },
                        new
                        {
                            Id = new Guid("471488cb-5306-46ed-883e-97fa1ec073b2"),
                            Name = "MANAGE_ORDERS"
                        },
                        new
                        {
                            Id = new Guid("995663ff-ec71-4c87-999d-2a617af718a4"),
                            Name = "MANAGE_SERVICE_TEMPLATES"
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            Name = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            Name = "PROJECT_MANAGER"
                        },
                        new
                        {
                            Id = new Guid("4bafb3e3-7675-462f-8b88-a2fae1402ceb"),
                            Name = "RESOURCE_MANAGER"
                        },
                        new
                        {
                            Id = new Guid("b23e199b-dfaa-4a35-97a8-6af5bb6682d7"),
                            Name = "LOCALIZATION_TEAM"
                        },
                        new
                        {
                            Id = new Guid("d306c1a7-7810-4363-8816-7459a1bb18d8"),
                            Name = "TALENT"
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.RolePrivilege", b =>
                {
                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrivilegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("RolePrivileges");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("76202262-ad72-41b1-9184-6c1934e0d85a"),
                            Id = new Guid("ef1e03d7-1154-42f9-9a5b-d6c2d32c2373")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("51d3cc91-396d-4c1b-a400-3484dedaa21a"),
                            Id = new Guid("4a43b9d0-1ddf-4e2d-9353-40b75c78312f")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("d50920b7-db8c-4300-9b10-c7f35febb5c7"),
                            Id = new Guid("5e185e09-f99f-4e58-9337-d9c3aa619969")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("301940eb-2f5c-4d01-aa1a-01694da06a7c"),
                            Id = new Guid("2b1d261f-6ecd-4d47-b156-97137b43dee7")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("f90b00af-b217-4714-b638-adcb9248e885"),
                            Id = new Guid("b8ee6d37-e0f5-4b7c-8d71-299f2564b3e3")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("63b82dde-6c06-4b2d-aeeb-32f4fb93b7ff"),
                            Id = new Guid("99f1f7d3-4c0a-4b85-a888-9a95cca8ba84")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("489bbacf-f6ac-4a80-bf33-a89473839c5d"),
                            Id = new Guid("6b0e2b66-b1b9-41aa-b487-ae4509df91ff")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("8e83760d-1a14-4d55-9fab-bd4ddc082894"),
                            Id = new Guid("6848d5b3-6aca-41ad-bf21-398d23f1acfc")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("5917352e-896c-4b77-a074-cabb3d6cae1b"),
                            Id = new Guid("e4bc7792-d40b-4408-bce5-be15be8ee4b4")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("a8dcdd64-261a-4408-ad1c-905d580ebb82"),
                            Id = new Guid("dba1592d-1bb1-45d6-b5b3-53d667148aa2")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("9c8533af-3487-4fad-9667-2d93f5cc9fda"),
                            Id = new Guid("2bc6c19a-df12-448c-b3fa-a9f0a6d8ea1b")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("471488cb-5306-46ed-883e-97fa1ec073b2"),
                            Id = new Guid("74be5836-2821-4865-b598-81f56c7b08a9")
                        },
                        new
                        {
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            PrivilegeId = new Guid("995663ff-ec71-4c87-999d-2a617af718a4"),
                            Id = new Guid("fc8aa44d-8df8-4522-8b7d-cc8256689bc1")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("301940eb-2f5c-4d01-aa1a-01694da06a7c"),
                            Id = new Guid("ef477335-b946-4059-8ec5-8a5f87f9ed48")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("f90b00af-b217-4714-b638-adcb9248e885"),
                            Id = new Guid("1c0a093c-005a-46d5-ab2e-4e0abd227d66")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("63b82dde-6c06-4b2d-aeeb-32f4fb93b7ff"),
                            Id = new Guid("772b2f57-2492-45d8-b822-1521fd392c8d")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("489bbacf-f6ac-4a80-bf33-a89473839c5d"),
                            Id = new Guid("002c4267-ccb1-4840-9e7b-8d6e92b0e52c")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("8e83760d-1a14-4d55-9fab-bd4ddc082894"),
                            Id = new Guid("b00a2d25-f9aa-4aea-afa3-c74c2aa7bb0f")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("5917352e-896c-4b77-a074-cabb3d6cae1b"),
                            Id = new Guid("ec12f797-d476-4cff-9bd6-6292cc9aaca1")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("a8dcdd64-261a-4408-ad1c-905d580ebb82"),
                            Id = new Guid("4c98e5ad-ec24-45fd-a070-0357dda2d277")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("9c8533af-3487-4fad-9667-2d93f5cc9fda"),
                            Id = new Guid("c8c13c16-9fed-438d-b0b2-fe3d4ca206cb")
                        },
                        new
                        {
                            RoleId = new Guid("29aa2668-12d1-484b-b04b-93b5d380c114"),
                            PrivilegeId = new Guid("471488cb-5306-46ed-883e-97fa1ec073b2"),
                            Id = new Guid("baf3088d-78a1-4a8a-98e5-e643a2dd13bc")
                        },
                        new
                        {
                            RoleId = new Guid("4bafb3e3-7675-462f-8b88-a2fae1402ceb"),
                            PrivilegeId = new Guid("8e83760d-1a14-4d55-9fab-bd4ddc082894"),
                            Id = new Guid("8f825e74-9694-41ac-a00b-3f183b7e65ce")
                        },
                        new
                        {
                            RoleId = new Guid("4bafb3e3-7675-462f-8b88-a2fae1402ceb"),
                            PrivilegeId = new Guid("5917352e-896c-4b77-a074-cabb3d6cae1b"),
                            Id = new Guid("222e8cc1-48e0-4a1c-bdee-3820dcbe5db5")
                        },
                        new
                        {
                            RoleId = new Guid("4bafb3e3-7675-462f-8b88-a2fae1402ceb"),
                            PrivilegeId = new Guid("a8dcdd64-261a-4408-ad1c-905d580ebb82"),
                            Id = new Guid("10572898-1050-40ea-a56d-49a0a2447c96")
                        },
                        new
                        {
                            RoleId = new Guid("b23e199b-dfaa-4a35-97a8-6af5bb6682d7"),
                            PrivilegeId = new Guid("8e83760d-1a14-4d55-9fab-bd4ddc082894"),
                            Id = new Guid("86415695-3c6c-4813-a702-cbadbf19fcca")
                        },
                        new
                        {
                            RoleId = new Guid("b23e199b-dfaa-4a35-97a8-6af5bb6682d7"),
                            PrivilegeId = new Guid("f90b00af-b217-4714-b638-adcb9248e885"),
                            Id = new Guid("63ff295e-b36b-4fb8-a990-9fc42b604309")
                        },
                        new
                        {
                            RoleId = new Guid("b23e199b-dfaa-4a35-97a8-6af5bb6682d7"),
                            PrivilegeId = new Guid("63b82dde-6c06-4b2d-aeeb-32f4fb93b7ff"),
                            Id = new Guid("8e112381-54ce-4d40-a63b-7953211f5d8b")
                        },
                        new
                        {
                            RoleId = new Guid("b23e199b-dfaa-4a35-97a8-6af5bb6682d7"),
                            PrivilegeId = new Guid("5917352e-896c-4b77-a074-cabb3d6cae1b"),
                            Id = new Guid("bfd8e8bb-0966-4337-9c5b-82b906ee6549")
                        },
                        new
                        {
                            RoleId = new Guid("b23e199b-dfaa-4a35-97a8-6af5bb6682d7"),
                            PrivilegeId = new Guid("489bbacf-f6ac-4a80-bf33-a89473839c5d"),
                            Id = new Guid("05bc9cf0-f573-4997-92fa-d147df9cacbb")
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("RoleId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2023, 9, 5, 20, 20, 51, 227, DateTimeKind.Local).AddTicks(5607),
                            Firstname = "Admin",
                            Lastname = "Yopmail",
                            Password = "$2a$11$czrwjGpSHr/CRlcWWX4Pd.lv0.HOB4L1/C7fuPOwvYhxfpYZsCjG6",
                            PhoneNumber = "0333333333",
                            RoleId = new Guid("0fc336a2-1400-43b5-8806-891c9bbefb3b"),
                            Status = 1,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2023, 9, 5, 20, 20, 51, 227, DateTimeKind.Local).AddTicks(5607),
                            Username = "admin.dotnetstarter@yopmail.com"
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.UserPrivilege", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrivilegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "PrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.ToTable("UserPrivileges");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("76202262-ad72-41b1-9184-6c1934e0d85a"),
                            Id = new Guid("f99ae8aa-51c0-4a35-9b3f-fd15002befd3")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("51d3cc91-396d-4c1b-a400-3484dedaa21a"),
                            Id = new Guid("05a6680c-757f-40dd-b033-60f8582bc28b")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("d50920b7-db8c-4300-9b10-c7f35febb5c7"),
                            Id = new Guid("76e8db09-b267-4319-85ba-00c78e765f04")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("301940eb-2f5c-4d01-aa1a-01694da06a7c"),
                            Id = new Guid("b42f2859-a19c-49dd-98bb-01a96b74876c")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("f90b00af-b217-4714-b638-adcb9248e885"),
                            Id = new Guid("11af8c9e-cfe4-4894-9dea-53538477812a")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("63b82dde-6c06-4b2d-aeeb-32f4fb93b7ff"),
                            Id = new Guid("ebdb3b1f-e6c9-4687-9460-6593cf9afa71")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("489bbacf-f6ac-4a80-bf33-a89473839c5d"),
                            Id = new Guid("a09dfbdd-1afd-4bec-b2bf-c7241b1826a8")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("8e83760d-1a14-4d55-9fab-bd4ddc082894"),
                            Id = new Guid("d157a0ff-9e33-47fc-8868-b40c5425a00d")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("5917352e-896c-4b77-a074-cabb3d6cae1b"),
                            Id = new Guid("1887c0e7-13fa-4a4f-b7e5-772754bc2008")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("a8dcdd64-261a-4408-ad1c-905d580ebb82"),
                            Id = new Guid("dde9988b-9066-4d0f-ae02-4593b6a96b3c")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("9c8533af-3487-4fad-9667-2d93f5cc9fda"),
                            Id = new Guid("f5b40ad7-0a50-4bd3-92be-2278dda51b54")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("471488cb-5306-46ed-883e-97fa1ec073b2"),
                            Id = new Guid("7f0e1a50-0fd3-4da8-bd1c-cfde7cfb7bc2")
                        },
                        new
                        {
                            UserId = new Guid("8c2cda55-eb4b-4ea3-ba52-6eaecf9a1661"),
                            PrivilegeId = new Guid("995663ff-ec71-4c87-999d-2a617af718a4"),
                            Id = new Guid("db328eef-da81-4be8-8e51-57e85e0b33ea")
                        });
                });

            modelBuilder.Entity("DotNetStarter.Entities.Otp", b =>
                {
                    b.HasOne("DotNetStarter.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetStarter.Entities.RolePrivilege", b =>
                {
                    b.HasOne("DotNetStarter.Entities.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetStarter.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotNetStarter.Entities.User", b =>
                {
                    b.HasOne("DotNetStarter.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotNetStarter.Entities.UserPrivilege", b =>
                {
                    b.HasOne("DotNetStarter.Entities.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetStarter.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
